import { IVendor, IVendorForm } from '@/types';

export const mockVendors: IVendor[] = [
  {
    id: '1',
    name: '코웨이',
    code: '1234567890',
    ceo: '홍길동',
    businessType: '제조업',
    businessItem: '가전제품',
    invoiceStatus: '사용',
    modifier: 'admin',
    modifiedAt: '2024-03-01T00:00:00Z',
    email: 'contact@coway.com'
  },
  {
    id: '2',
    name: '삼성전자',
    code: '9876543210',
    ceo: '김철수',
    businessType: '제조업',
    businessItem: '전자제품',
    invoiceStatus: '사용',
    modifier: 'admin',
    modifiedAt: '2024-03-01T00:00:00Z',
    email: 'contact@samsung.com'
  },
];

export const mockVendorForms: IVendorForm[] = [
  {
    id: 1,
    vendorName: '코웨이',
    vendorCode: '1234567890',
    ceo: '홍길동',
    invoiceItems: {
      paymentInfo: true,
      membership: false,
      barcode: true,
      orderNumber: true,
      productGroup: true,
      modelName: true,
      contractDate: true,
      mandatoryPeriod: true,
      contractPeriod: true,
      supplyPrice: true,
      vat: true,
      rentalFee: true,
      installationAddress: true,
      defaultInterest: true,
      note: false,
      asCharge: false,
      consumableReplacementCost: false,
      penaltyFee: false,
      branchName: false,
      contact: false,
    },
    callCenterInfo: '1588-5200, coway.com',
    paymentDescription: '고객이 제공한 결제정보에 의해 매월 25일 자동 결제됩니다.',
    createdBy: 'admin01',
    createdAt: '2024.03.01 13:11',
    updatedBy: 'admin02',
    updatedAt: '2024.03.05 11:50',
  },
  {
    id: 2,
    vendorName: '삼성전자',
    vendorCode: '9876543210',
    ceo: '김철수',
    invoiceItems: {
      paymentInfo: true,
      membership: true,
      barcode: false,
      orderNumber: true,
      productGroup: true,
      modelName: true,
      contractDate: true,
      mandatoryPeriod: true,
      contractPeriod: true,
      supplyPrice: true,
      vat: true,
      rentalFee: true,
      installationAddress: true,
      defaultInterest: true,
      note: true,
      asCharge: true,
      consumableReplacementCost: true,
      penaltyFee: false,
      branchName: false,
      contact: true,
    },
    callCenterInfo: '1588-3366, samsung.com',
    paymentDescription: '매월 1일 자동 결제되며, 미납 시 연체이자가 발생할 수 있습니다.',
    createdBy: 'admin01',
    createdAt: '2024.03.02 09:30',
    updatedBy: 'admin01',
    updatedAt: '2024.03.02 09:30',
  },
]; 